/**
 * Login actions
 */
export const LOGGING_START = 'LOGGING_START'
export const LOGGING_SUCCESS = 'LOGGING_SUCCESS'
export const LOGGING_FAILURE = 'LOGGING_FAILURE'

/**
 * Friends actions
 */
export const FETCH_FRIENDS_START = 'FETCH_FRIENDS_START'
export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS'
export const FETCH_FRIENDS_FAILURE = 'FETCH_FRIENDS_FAILURE'
export const UPDATE_FRIENDSHIP_SUCCESS = 'UPDATE_FRIENDSHIP_SUCCESS'
export const UPDATE_FRIENDSHIP_FAILURE = 'UPDATE_FRIENDSHIP_FAILURE'
export const DELETE_FRIENDSHIP = 'DELETE_FRIENDSHIP'
export const FETCH_USERS = 'FETCH_USERS'
export const FRIEND_USER = 'FRIEND_USER'

/**
 * Game actions
 */
export const FETCH_GAMES_START = 'FETCH_GAMES_START'
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS'
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE'
export const CREATE_GAME = 'CREATE_GAME'
export const JOIN_GAME = 'JOIN_GAME'
export const ADD_MEDIA_TO_GAME = 'ADD_MEDIA_TO_GAME'
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAM_SUCCESS'
export const JOINED_GAME_SUCCESS = 'JOINED_GAME_SUCCESS'
