/**
 * Login actions
 */
export const LOGGING_START = 'LOGGING_START';
export const LOGGING_SUCCESS = 'LOGGING_SUCCESS';
export const LOGGING_FAILURE = 'LOGGING_FAILURE';

/**
 * Friends actions
 */
export const FETCH_FRIENDS_START = 'FETCH_FRIENDS_START';
export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS';
export const FETCH_FRIENDS_FAILURE = 'FETCH_FRIENDS_FAILURE';

export const UPDATE_FRIENDSHIP_SUCCESS = 'UPDATE_FRIENDSHIP_SUCCESS';
export const UPDATE_FRIENDSHIP_FAILURE = 'UPDATE_FRIENDSHIP_FAILURE';
export const DELETE_FRIENDSHIP = 'DELETE_FRIENDSHIP';
